# Generated by Django 3.0.4 on 2020-03-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='genre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rentals.Genre'),
            preserve_default=False,
        ),
    ]
